title: "AI & Data Science"
email: vuvietduy1010@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: vuvietduy
paginate: 30
disqus: "demowebsite"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:

# Authors
authors:
  vuvietduy:
    name: VuVietDuy
    display_name: Vũ Viết Duy
    avatar:
    email: vuvietduy1010@gmail.com
    web: https://vuvietduy.github.ico
    twitter:
    description: ""

# Social
social:
  instagram:
  facebook: https://www.facebook.com/VuVietDuyy
  twitter:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
