title: "AI & Data Science"
email: vuvietduy1010@gmail.com
timezone: UTC
url: "https://vuvietduy.github.io"
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: vuvietduy
paginate: 30
disqus: "demowebsite"
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
sass:
  sass_dir: _sass
  style: :compressed
ganalytics:
toc:
  min_level: 1
  max_level: 4
  no_toc_section_class: "no_toc"
  list_class: "toc-list"
  sublist_class: "toc-sublist"
  item_class: "toc-item"
  item_prefix: "toc-"
repository: vuvietduy/vuvietduy.github.io

# Authors
authors:
  vuvietduy:
    name: VuVietDuy
    display_name: Vũ Viết Duy
    avatar:
    email: vuvietduy1010@gmail.com
    web: https://vuvietduy.github.io
    twitter:
    description: ""

# Social
social:
  instagram:
  facebook: https://www.facebook.com/VuVietDuyy
  twitter:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-toc
